const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const noop=()=>{},ctx=new Proxy({},{get:()=>noop,set:()=>true});const classes=new Set(['choosing']);const el=()=>({hidden:false,dataset:{},classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),contains:x=>classes.has(x)},setAttribute:noop,removeAttribute:noop,addEventListener:noop,append:noop,focus:noop,click(){this.onclick?.()}});const nodes={};const document={body:el(),createElement:el,querySelector:s=>nodes[s]??=(s==='#lcd'?{...el(),getContext:()=>ctx}:el()),querySelectorAll:()=>[],addEventListener:noop};const box={document,window:{addEventListener:noop},localStorage:{getItem:()=>0,setItem:noop},requestAnimationFrame:noop,setTimeout:()=>1,clearTimeout:noop,Math,Set,Map};vm.createContext(box);vm.runInContext(fs.readFileSync('dist/game.js','utf8')+fs.readFileSync('dist/phones.js','utf8')+';sound=false',box);const run=s=>vm.runInContext(s,box);for(const id of ['1100','3310','6600','3220']){run(`selectPhone('${id}')`);for(let i=0;i<run(`phones[phoneId].ids.length`);i++){run(`state='games';gameChoice=${i};action('5');draw();action('5');draw();for(let n=0;n<30;n++)update(.016);draw();action('hash');draw()`);assert.equal(run('state'),'pause',id+' pause');run("action('5');action('back');action('back');draw()")}}run("selectPhone('3310');extra='bantumi';startExtra();sow(extraState,2,0)");assert.equal(run('extraState.pits.reduce((a,b)=>a+b,0)'),48);assert.equal(run('extraState.turn'),0);run("extra='mix';startExtra();extraState.tiles=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,0,15];extraState.blank=14;extraInput('6')");assert.equal(run('state'),'win');run("extra='pairs';startExtra();extraState.cards=[0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7];for(let i=0;i<16;i++){extraState.cursor=i;extraInput('5')}");assert.equal(run('state'),'win');run("extra='dance';startExtra();extraState.t=2;extraInput('4')");assert.equal(run('extraState.hits'),1);run("extra='spider';startExtra();for(let i=0;i<6;i++){extraState.items=[];update(.01)}");assert.equal(run('state'),'win');console.log('PASS: 4 phone menus, every game starts/draws/pauses, Bantumi seed conservation/extra turn, puzzle wins, rhythm scoring, shooter progression');

for(const [x,y,key] of [[0,-1,"up"],[0,1,"down"],[-1,0,"left"],[1,0,"right"]])assert.equal(run(`joystickDirection(${x},${y})`),key);assert.equal(run("joystickDirection(0,0)"),null);run("selectPhone('6600');joyPointer=1;steerJoystick('down')");assert.equal(run("gameChoice"),1);run("resetJoystick();game='snake';extra=null;snakeStart();joyPointer=2;steerJoystick('up')");assert.ok(run("held.has('up')&&turns[0].y===-1"));run("resetJoystick()");assert.ok(run("!held.has('up')&&joyPointer===null"));console.log("PASS: joystick four directions, dead zone, menu selection, Snake steering, release cleanup");
// Regression checks for each shipped engine and its end-state behavior.
run("selectPhone('3220');extra='dance';startExtra();for(let i=0;i<5100;i++)update(.01)");assert.equal(run('state'),'over','missing every rhythm note must fail');
run("extra='dance';startExtra();for(let i=0;i<72;i++){extraState.t=extraState.schedule[i].at;extraInput(['4','2','8','6'][extraState.schedule[i].lane])}extraState.t=50;update(.01)");assert.equal(run('state'),'win');assert.equal(run('extraState.hits'),72);
run("extra='pinball';startExtra();extraState.ball={x:48,y:42,vx:0,vy:0,ready:false};update(0)");assert.ok(run('Number.isFinite(extraState.ball.vx)&&Number.isFinite(extraState.ball.vy)'),'bumper centre stays finite');
run("for(let i=0;i<3;i++){extraState.ball={x:96,y:131,vx:0,vy:1,ready:false};update(.01)}");assert.equal(run('state'),'over');run("action('5')");assert.equal(run('extraState.lives'),3,'pinball retry resets lives');
run("extra='spider';startExtra();extraState.cool=0;extraInput('ok')");assert.equal(run('extraState.shots.length'),1,'joystick centre fires');run("extraState.inv=0;extraState.shots=[{x:extraState.x,y:109,vy:50}];update(.01)");assert.equal(run('extraState.lives'),2);run("state='pause';var savedTime=extraState.t;update(1)");assert.equal(run('extraState.t'),run('savedTime'));
run("selectPhone('3310');extra='bantumi';startExtra();for(let step=0;step<2000&&state==='play';step++){const side=extraState.turn;const start=side?7:0;const opts=Array.from({length:6},(_,i)=>start+i).filter(i=>extraState.pits[i]>0);sow(extraState,opts[step%opts.length],side);if(extraState.pits.reduce((a,b)=>a+b,0)!==48)throw Error('Lost seeds')}");assert.equal(run('state'),'win','Bantumi completes full game');
run("extra='pairs';startExtra();extraState.cards=[0,1,0,1,2,2,3,3,4,4,5,5,6,6,7,7];extraInput('5');extraInput('6');extraInput('5');update(.9)");assert.equal(run('extraState.open.length'),0,'mismatches conceal');
for(let m=0;m<6;m++){run(`extra=null;game='snake';maze=${m};snakeStart()`);assert.ok(run('!snake.some(p=>walls.some(w=>same(p,w)))'),'snake starts clear of walls '+m)}
run("selectPhone('3310');game='impact';newGame();level=8;resetLevel();bossDone=true;transition=0;impactUpdate(.01)");assert.equal(run('state'),'win','3310 ends at 8 stages');
console.log('PASS: rhythm perfect/fail, pinball collision/lives/retry, spider fire/damage/pause, complete Bantumi, card conceal, all Snake mazes, 3310 finale');
